config/routes.rb
Rails.application.routes.draw do
  resources :resultados
  resources :estandars
  resources :ficheros
  get "archivos/subir_archivos"
  post "archivos/subir_archivos"
  get "archivos/listar_archivos"
  post "archivos/borrar_archivos"
  get "archivos/valida"

   root 'archivos#subir_archivos'

end

app/models/fichero.rb
class Fichero < ActiveRecord::Base
end

app/controllers/ficheros_controller.rb
class FicherosController < ApplicationController
  require 'rubygems'
  require 'nokogiri'

  before_action :set_fichero, only: [:show, :edit, :update, :destroy]

  # GET /ficheros
  # GET /ficheros.json
  def index
    @ficheros = Fichero.all
  end

# GET /ficheros/1
  # GET /ficheros/1.json
  def show
  end

  # GET /ficheros/new
  def new
    @fichero = Fichero.new
  end

  # GET /ficheros/1/edit
  def edit
  end

  # POST /ficheros
  # POST /ficheros.json
  def create
    @fichero = Fichero.new(fichero_params)

    respond_to do |format|
      if @fichero.save
        format.html { redirect_to @fichero, notice: 'Fichero was successfully created.' }
        format.json { render :show, status: :created, location: @fichero }
      else
        format.html { render :new }
        format.json { render json: @fichero.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ficheros/1
  # PATCH/PUT /ficheros/1.json
  def update
    respond_to do |format|
      if @fichero.update(fichero_params)
        format.html { redirect_to @fichero, notice: 'Fichero was successfully updated.' }
        format.json { render :show, status: :ok, location: @fichero }
      else
        format.html { render :edit }
        format.json { render json: @fichero.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ficheros/1
  # DELETE /ficheros/1.json
  def destroy
    @fichero.destroy
    respond_to do |format|
      format.html { redirect_to ficheros_url, notice: 'Fichero was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fichero
      @fichero = Fichero.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fichero_params
      params.require(:fichero).permit(:nombre, :tiempoVal, :rank, :fecha_crea)
    end
end

app/helpers/ficheros_helper.rb
module FicherosHelper
end

app/views/ficheros/_form.html.erb
<%= form_for(@fichero) do |f| %>
  <% if @fichero.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fichero.errors.count, "error") %> prohibited this fichero from being saved:</h2>

      <ul>
      <% @fichero.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :tiempoVal %><br>
    <%= f.text_field :tiempoVal %>
  </div>
  <div class="field">
    <%= f.label :rank %><br>
    <%= f.number_field :rank %>
  </div>
  <div class="field">
    <%= f.label :fecha_crea %><br>
    <%= f.datetime_select :fecha_crea %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ficheros/edit.html.erb
<h1>Editing Fichero</h1>

<%= render 'form' %>

<%= link_to 'Show', @fichero %> |
<%= link_to 'Back', ficheros_path %>

app/views/ficheros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ficheros</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Tiempoval</th>
      <th>Rank</th>
      <th>Fecha crea</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ficheros.each do |fichero| %>
      <tr>
        <td><%= fichero.nombre %></td>
        <td><%= fichero.tiempoVal %></td>
        <td><%= fichero.rank %></td>
        <td><%= fichero.fecha_crea %></td>
        <td><%= link_to 'Show', fichero %></td>
        <td><%= link_to 'Edit', edit_fichero_path(fichero) %></td>
        <td><%= link_to 'Destroy', fichero, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fichero', new_fichero_path %>

app/views/ficheros/new.html.erb
<h1>New Fichero</h1>

<%= render 'form' %>

<%= link_to 'Back', ficheros_path %>

app/views/ficheros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @fichero.nombre %>
</p>

<p>
  <strong>Tiempoval:</strong>
  <%= @fichero.tiempoVal %>
</p>

<p>
  <strong>Rank:</strong>
  <%= @fichero.rank %>
</p>

<p>
  <strong>Fecha crea:</strong>
  <%= @fichero.fecha_crea %>
</p>

<%= link_to 'Edit', edit_fichero_path(@fichero) %> |
<%= link_to 'Back', ficheros_path %>