config/routes.rb
Rails.application.routes.draw do
  resources :resultados
  resources :estandars
  resources :ficheros
  get "archivos/subir_archivos"
  post "archivos/subir_archivos"
  get "archivos/listar_archivos"
  post "archivos/borrar_archivos"
  get "archivos/valida"

   root 'archivos#subir_archivos'

end

app/models/estandar.rb
class Estandar < ActiveRecord::Base
end

app/controllers/estandars_controller.rb
class EstandarsController < ApplicationController
  before_action :set_estandar, only: [:show, :edit, :update, :destroy]

  # GET /estandars
  # GET /estandars.json
  def index
    @estandars = Estandar.all
  end

  # GET /estandars/1
  # GET /estandars/1.json
  def show
  end

  # GET /estandars/new
  def new
    @estandar = Estandar.new
  end

  # GET /estandars/1/edit
  def edit
  end

  # POST /estandars
  # POST /estandars.json
  def create
    @estandar = Estandar.new(estandar_params)

    respond_to do |format|
      if @estandar.save
        format.html { redirect_to @estandar, notice: 'Estandar was successfully created.' }
        format.json { render :show, status: :created, location: @estandar }
      else
        format.html { render :new }
        format.json { render json: @estandar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estandars/1
  # PATCH/PUT /estandars/1.json
  def update
    respond_to do |format|
      if @estandar.update(estandar_params)
        format.html { redirect_to @estandar, notice: 'Estandar was successfully updated.' }
        format.json { render :show, status: :ok, location: @estandar }
      else
        format.html { render :edit }
        format.json { render json: @estandar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estandars/1
  # DELETE /estandars/1.json
  def destroy
    @estandar.destroy
    respond_to do |format|
      format.html { redirect_to estandars_url, notice: 'Estandar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estandar
      @estandar = Estandar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estandar_params
      params.require(:estandar).permit(:tipo, :descripcion, :fecha_crea)
    end
end

app/helpers/estandars_helper.rb
module EstandarsHelper
end

app/views/estandars/_form.html.erb
<%= form_for(@estandar) do |f| %>
  <% if @estandar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@estandar.errors.count, "error") %> prohibited this estandar from being saved:</h2>

      <ul>
      <% @estandar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tipo %><br>
    <%= f.text_field :tipo %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_field :descripcion %>
  </div>
  <div class="field">
    <%= f.label :fecha_crea %><br>
    <%= f.datetime_select :fecha_crea %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/estandars/edit.html.erb
<h1>Editing Estandar</h1>

<%= render 'form' %>

<%= link_to 'Show', @estandar %> |
<%= link_to 'Back', estandars_path %>

app/views/estandars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Estandars</h1>

<table>
  <thead>
    <tr>
      <th>Tipo</th>
      <th>Descripcion</th>
      <th>Fecha crea</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @estandars.each do |estandar| %>
      <tr>
        <td><%= estandar.tipo %></td>
        <td><%= estandar.descripcion %></td>
        <td><%= estandar.fecha_crea %></td>
        <td><%= link_to 'Show', estandar %></td>
        <td><%= link_to 'Edit', edit_estandar_path(estandar) %></td>
        <td><%= link_to 'Destroy', estandar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Estandar', new_estandar_path %>

app/views/estandars/new.html.erb
<h1>New Estandar</h1>

<%= render 'form' %>

<%= link_to 'Back', estandars_path %>

app/views/estandars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo:</strong>
  <%= @estandar.tipo %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @estandar.descripcion %>
</p>

<p>
  <strong>Fecha crea:</strong>
  <%= @estandar.fecha_crea %>
</p>

<%= link_to 'Edit', edit_estandar_path(@estandar) %> |
<%= link_to 'Back', estandars_path %>