config/routes.rb
Rails.application.routes.draw do
  resources :resultados
  resources :estandars
  resources :ficheros
  get "archivos/subir_archivos"
  post "archivos/subir_archivos"
  get "archivos/listar_archivos"
  post "archivos/borrar_archivos"
  get "archivos/valida"

   root 'archivos#subir_archivos'

end

app/models/resultado.rb
class Resultado < ActiveRecord::Base
  belongs_to :fichero
  belongs_to :estandar
end

app/controllers/resultados_controller.rb
class ResultadosController < ApplicationController
  before_action :set_resultado, only: [:show, :edit, :update, :destroy]

  # GET /resultados
  # GET /resultados.json
  def index
    @resultados = Resultado.all
  end

  # GET /resultados/1
  # GET /resultados/1.json
  def show
  end

  # GET /resultados/new
  def new
    @resultado = Resultado.new
  end

  # GET /resultados/1/edit
  def edit
  end

  # POST /resultados
  # POST /resultados.json
  def create
    @resultado = Resultado.new(resultado_params)

    respond_to do |format|
      if @resultado.save
        format.html { redirect_to @resultado, notice: 'Resultado was successfully created.' }
        format.json { render :show, status: :created, location: @resultado }
      else
        format.html { render :new }
        format.json { render json: @resultado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resultados/1
  # PATCH/PUT /resultados/1.json
  def update
    respond_to do |format|
      if @resultado.update(resultado_params)
        format.html { redirect_to @resultado, notice: 'Resultado was successfully updated.' }
        format.json { render :show, status: :ok, location: @resultado }
      else
        format.html { render :edit }
        format.json { render json: @resultado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resultados/1
  # DELETE /resultados/1.json
  def destroy
    @resultado.destroy
    respond_to do |format|
      format.html { redirect_to resultados_url, notice: 'Resultado was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resultado
      @resultado = Resultado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resultado_params
      params.require(:resultado).permit(:codError, :msg_error, :fecha_crea, :fichero_id, :estandar_id)
    end
end

app/helpers/resultados_helper.rb
module ResultadosHelper
end

app/views/resultados/_form.html.erb
<%= form_for(@resultado) do |f| %>
  <% if @resultado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resultado.errors.count, "error") %> prohibited this resultado from being saved:</h2>

      <ul>
      <% @resultado.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :codError %><br>
    <%= f.number_field :codError %>
  </div>
  <div class="field">
    <%= f.label :msg_error %><br>
    <%= f.text_field :msg_error %>
  </div>
  <div class="field">
    <%= f.label :fecha_crea %><br>
    <%= f.datetime_select :fecha_crea %>
  </div>
  <div class="field">
    <%= f.label :fichero_id %><br>
    <%= f.text_field :fichero_id %>
  </div>
  <div class="field">
    <%= f.label :estandar_id %><br>
    <%= f.text_field :estandar_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resultados/edit.html.erb
<h1>Editing Resultado</h1>

<%= render 'form' %>

<%= link_to 'Show', @resultado %> |
<%= link_to 'Back', resultados_path %>

app/views/resultados/index.html.erb
<div class="alert alert-info alert-dismissable" id="notice">
  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
  <strong>Success!</strong> <%= notice %>
</div>

<br/>
<div class="container">
<% mis_estandares = Estandar.all%>
  <div class="panel-group" id="accordion">
      <% mis_estandares.each do |mi_estandar| %>
      <% resultado_bad = Resultado.where(:estandar_id => mi_estandar.id, :codError=>1).count%>
    <% if resultado_bad == 0%>
    <div class="panel panel-success">
      <%else%>
        <div class="panel panel-danger">
    <%end%>
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#collapse<%=mi_estandar.id%>">
          <%=mi_estandar.descripcion%></a>
        </h4>
      </div>
      <div id="collapse<%=mi_estandar.id%>" class="panel-collapse collapse">
        <div class="panel-body">
          <% if resultado_bad == 0%>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit,
        sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
        minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
        commodo consequat.
        <%else%>
        <% mis_resultados = Resultado.where(estandar_id:mi_estandar.id,codError:1)%>
        <table class="table">
          <thead>
            <tr>
              <th>Fichero</th>
              <th>Estandar</th>
              <th>Mensaje Error</th>
              <th>Ayuda</th>
              <th colspan="6"></th>
            </tr>
          </thead>

          <tbody>
            <% mis_resultados.each do |res| %>
            <% mi_fichero = Fichero.find_by(id: res.fichero_id)%>
              <tr>
                <td><%= mi_fichero.nombre %></td>
                <td><%= mi_estandar.descripcion %></td>
                <td><%= res.msg_error %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%end%>

      </div>
      </div>
    </div>
<%end%>
  </div>




</div>

app/views/resultados/new.html.erb
<h1>New Resultado</h1>

<%= render 'form' %>

<%= link_to 'Back', resultados_path %>

app/views/resultados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Coderror:</strong>
  <%= @resultado.codError %>
</p>

<p>
  <strong>Msg error:</strong>
  <%= @resultado.msg_error %>
</p>

<p>
  <strong>Fecha crea:</strong>
  <%= @resultado.fecha_crea %>
</p>

<p>
  <strong>Fichero:</strong>
  <%= @resultado.fichero %>
</p>

<p>
  <strong>Estandar:</strong>
  <%= @resultado.estandar %>
</p>

<%= link_to 'Edit', edit_resultado_path(@resultado) %> |
<%= link_to 'Back', resultados_path %>